[project]
org-name = "chanakal"
version = "0.1.0"
authors = ["Chanaka Lakmal"]
keywords = ["shoutout", "sms", "otp"]
repository = "https://github.com/ldclakmal/package-shoutout"
license = "Apache-2.0"

[dependencies]